### ISSUE TITLE
Failed to connect to https://api.storyscript.io/graphql

### ISSUE THREAD

**Issue by darkLord19** [storyscript/platform-graphql#8]
On running story deploy --hard I got this error 2-3 times out of 5 times and also got it once for story deploy in past 1.5 hours

**Comment by JeanBarriere** [comment]
@darkLord19 May come from your internet connection, or a maintenance on storyscript. Should not happen a lot

**Comment by stevepeak** [comment]
Closing as assumed not an issue anymore. Please feel free to comment if it occurs again 👍
